spring:
  rabbitmq:
    host: rabbitmq3

app:
  rabbitmq:
    pizzas-added-notification: q.pizzas-added-notification

server:
  port: 0


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/