spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2_restaurant_service?useSSL=false
    username: gian
    password: Gianluca
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  rabbitmq:
    host: rabbitmq3

server:
  port: 0
  servlet:
    context-path: /api

app:
  pizza-service-url: http://gateway-service:8080/api/pizzas/restaurant
  rabbitmq:
    add-pizzas-routingkey: q.add-pizzas-to-restaurant
    pizzas-added-routingkey: q.pizzas-added-to-restaurant
    pizzas-added-notification: q.pizzas-added-notification


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

management:
  health:
    circuitbreaker:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    instances:
      aggiungiPizzasToRestaurant:
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: count-based
        sliding-window-size: 5
        minimum-number-of-calls: 5
        slow-call-duration-threshold: 10s
        slow-call-rate-threshold: 60
        failure-rate-threshold: 60