spring:
  main:
    allow-circular-references: true
  zipkin:
    base-url: http://localhost:9411

app:
  rabbitmq:
    pizzas-added-notification: q.pizzas-added-notification

server:
  port: 0


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/