spring:
  main:
    allow-circular-references: true
  zipkin:
    base-url: http://localhost:9411
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2_pizza_service?useSSL=false
    username: gian
    password: Gianluca
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

  mvc:
    path match:
      matching-strategy: ant_path_matcher

server:
  port: 0
  servlet:
    context-path: /api

app:
  rabbitmq:
    #coda da cui riceve il payload
    add-pizzas-routingkey: q.add-pizzas-to-restaurant
    #coda su cui darà risposta
    pizzas-added-routingkey: q.pizzas-added-to-restaurant
    #coda che mi occorre per la notifica di avvetuno processo
    pizzas-added-notification: q.pizzas-added-notification

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/