spring:
  rabbitmq:
    host: 172.18.0.3
  main:
    allow-circular-references: true
  zipkin:
    base-url: http://172.18.0.3:9411
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2_restaurant_service?useSSL=false
    username: gian
    password: Gianluca
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

  mvc:
    path match:
      matching-strategy: ant_path_matcher

server:
  port: 0
  servlet:
    context-path: /api

app:
  pizza-service-url: http://172.18.0.3:8080/api/pizzas/restaurant
  rabbitmq:
    add-pizzas-routingkey: q.add-pizzas-to-restaurant
    pizzas-added-routingkey: q.pizzas-added-to-restaurant
    pizzas-added-notification: q.pizzas-added-notification


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://172.18.0.3:8761/eureka/